# Generated by Django 5.0.1 on 2024-01-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('prioridad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('usuarios', models.ManyToManyField(to='app.usuario')),
            ],
        ),
    ]
